{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "cisco-exporter.fullname" . }}
  labels:
    release: {{ .Values.monitoring.release }}
spec:
  jobLabel: cisco-exporter
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cisco-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  podMetricsEndpoints:
    - interval: {{ .Values.monitoring.interval }}
      path: /metrics
      port: {{ .Values.service.name }}
{{- end }}
