apiVersion: v1
kind: Service
metadata:
  name: {{ include "cisco-exporter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cisco-exporter.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "cisco-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
